version: '{build}'
os: Windows Server 2012
install:
  - choco install sbt
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - sbt clean compile
test_script:
  - sbt "test-only * -- -n windows"
  - sbt "scripted universal/dist universal/stage windows/java-app-archetype windows/test-custom-main"
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
